### PR TITLE
Failed disaster recovery should indicate whether partial updates have been made

### LINKED ISSUE #260: Failed disaster recovery should indicate whether partial updates have been made

### PR DESCRIPTION
**Pull request by krasserm**
- closes #260

### CODE REVIEW

File: eventuate-core/src/main/scala/com/rbmhtechnology/eventuate/ReplicationEndpoint.scala [hunk 1]
```diff
@@ -281,11 +284,15 @@ class ReplicationEndpoint(
...
+      }
+
       val recoveryOperation = for {
-        infos <- recovery.readEndpointInfos
-        clocks <- recovery.readEventLogClocks
+        infos <- recovery.readEndpointInfos.recoverWith(recoveryFailure(partialUpdate = false))
+        clocks <- recovery.readEventLogClocks.recoverWith(recoveryFailure(partialUpdate = false))
         links = recovery.recoveryLinks(infos, clocks)
-        _ <- recovery.deleteSnapshots(links)
+        _ <- recovery.deleteSnapshots(links).recoverWith(recoveryFailure(partialUpdate = true))
```
Comment (magro) [inline eventuate-core/src/main/scala/com/rbmhtechnology/eventuate/ReplicationEndpoint.scala]: Just to be sure: Is `partialUpdate = true` here because the application might have deleted events under the assumption that the state is stored in the snapshot?

**Comment by magro** [comment]
What about a minor doc update?

File: eventuate-core/src/main/scala/com/rbmhtechnology/eventuate/ReplicationEndpoint.scala (hunk 1 above)
Comment (krasserm) [inline eventuate-core/src/main/scala/com/rbmhtechnology/eventuate/ReplicationEndpoint.scala]: Snapshots that cover events that have been lost during a disaster must be removed. This is what  `recovery.deleteSnapshots(links)` is doing. If this operation fails, `partialUpdate` is set to `true` because it might have partially deleted some local snapshots already.

**Comment by krasserm** [comment]
I'm a bit hesitant adding it to the reference documentation, as I'm not sure yet how disaster recovery will evolve in the next release (discussion to be done). It's anyway documented in the API docs. I'd rather like to extend the reference documentation later when we agreed upon how to proceed with disaster recovery in context of #142.

**Comment by volkerstampa** [comment]
LGTM

File: eventuate-core/src/main/scala/com/rbmhtechnology/eventuate/ReplicationEndpoint.scala (hunk 1 above)
Comment (magro) [inline eventuate-core/src/main/scala/com/rbmhtechnology/eventuate/ReplicationEndpoint.scala]: Ok. Learning eventuate more and more.

Btw: would it be a possible optimization to compare received `infos` and `clocks` with the locally stored data and abort/skip recovery (and this snapshot deletion)?

Comment (krasserm) [inline eventuate-core/src/main/scala/com/rbmhtechnology/eventuate/ReplicationEndpoint.scala]: Yes, we could consider that when evolving disaster recovery.

**Comment by krasserm** [comment]
Thanks for the review @magro and @volkerstampa
